#import "/funcs.typ": *

#chapter("The King’s Courtyard")

Gaelwyn often wondered what he would be without Welexi. His life had changed the day he’d found the world’s greatest hero laying broken beneath an olive tree. The story was different every time Welexi told it, which had bothered Gaelwyn at first. In the Sovento States it was an orange tree, fully in bloom but not yet ripe with fruit. When the story was told in Maskoy, the tree became a fig tree, with fruits spoiling on the ground. Far to the south in Malwin, Welexi had claimed to be bleeding freely, staining the ground rust-red, but to the east in Palao the wounds were bloodless. It had taken Gaelwyn a long time to see what Welexi was doing; the stories were translations, not just conversions from one language to another, but from one culture to another. The fig tree was a symbol of peace in Maskoy. The people of Malwin would understand the blood-stained ground to be the epitome of martyrdom. Welexi was not lying; he was crafting an impression more real than truth.

In the stories, that single moment had marked Gaelwyn’s transition from horrible monster to humble doctor. Gaelwyn had never felt it, not in the moment and not at any point afterward. Welexi was the only one who believed that Gaelwyn had a seed of goodness in him at all, let alone that this seed still had the ability to grow. Gaelwyn had saved Welexi’s life and continued on through the strength of Welexi’s belief. The books that contained Gaelwyn’s life’s work had been burned save for a few copies held by those who knew the value of them. His hospital had been razed to the ground and his name had been smeared through the mud. Welexi offered a narrow path that might yet be walked, so Gaelwyn walked it.

They sat together in the darkness, leaning up against the gray glass boulder that Vidre had made. Vidre and Dominic slept within, using spare clothing to cushion their heads. There was no fire to keep them warm. Welexi was uncharacteristically dark as well, with no armor to keep him protected and no spear of light in hand. Castle Launtine loomed in the distance. Tomorrow they would make their assault. It wouldn’t do for someone to go investigating a fire in the woods; Welexi’s light would be even more suspicious. Dawn was coming; it wouldn’t be long until it would provide them with light and warmth.

“You worry about me,” said Welexi. His voice was barely above a whisper, both so that the other two wouldn’t wake and so no distant travelers would have a chance of hearing.

“It’s bad enough when you’re attacked,” said Gaelwyn. “It’s bad enough knowing that you’re out there fighting, that you might sustain any number of wounds I cannot fix. The anticipation of it … I don’t enjoy it.”

“I had a close call with Zerstor,” said Welexi. “I won’t come so close to death’s gateway again.”

“You’ll be fighting illustrati,” said Gaelwyn. “Death can come quickly.”

“You’ve seen the hits I can take,” said Welexi. “You’ve seen my skill at avoiding the worst attacks in the first place.”

“Yes,” said Gaelwyn. “But you’ve never fought a man with two domains before.”

Welexi glanced toward the glass shell with its gray, frosted glass, where Vidre and Dominic slept side by side. “Our information comes third hand,” he said slowly. “Vidre isn’t certain that we can trust it.”

Gaelwyn’s eyes widened. He had already been speaking at a whisper, but now he leaned forward. “What does that mean?”

“Many things,” said Welexi. “If Dominic is telling the truth, he was given information by way of Hartwain. Our enemy is clever enough to have used her against us. It is well possible that they could use their leverage to coerce whatever story they wanted. More seriously, it is possible that Dominic has been compromised.”

“How?” asked Gaelwyn. “We’ve been with him for weeks.”

“That is less clear,” said Welexi. He gazed at the sleeping form of Dominic. Gaelwyn felt an urge to reach out and touch him, just to confirm by the beating of his heart that he was asleep. “Vidre has her suspicions, which are so far difficult to distinguish from sheer paranoia. You heard the way that Dominic spoke back to me. How he’s questioned our actions. Vidre watched him walk from Hartwain’s house as though he were completely unconcerned with the possibility of ambush.” Welexi shrugged. “He and Vidre have something of a complicated relationship; it may simply be that it has soured. That would not be a first for Vidre.”

“We should hold off on the attack,” said Gaelwyn. “Castle Launtine can wait until we know more. Until we can be sure of where loyalties are.”

“No,” said Welexi. “Yesterday’s attacks were a grand play for power. Resources were spread thin to accomplish what they did. Castle Launtine should be poorly defended right now. We ran swiftly to get here; it is unlikely that reinforcements from Parance will arrive before we’re ready for the assault. If they have even half the capabilities we suspect, they grow more powerful with every passing week.” He stretched his arms. “Vidre and I should be able to take care of what’s there. Dominic will help us; this will be a test of his courage, his will, his prowess, and his loyalty.”

“I only wish I could do more to help,” said Gaelwyn. He folded his hands in his lap and felt the flesh of his body. Everything was working properly of course. He checked his muscles every few minutes, making small adjustments with every movement. His body was the height of efficiency, but his domain could propel it further when he was paying attention.

“You could fight,” said Welexi.

The sentence hung in the air, coiling around Gaelwyn like a snake.

“When Wealdwood forced his way aboard our ship in the middle of the night, coming to kill me, you disabled him,” said Welexi. “You placed your hand upon his armored chest and twisted his insides just so. You did not hurt him, only stopped him from taking my life.”

“You’re asking me to break a vow I made,” said Gaelwyn.

“I’m not asking,” said Welexi. “I’m only stating a truth. You could fight alongside us. You would not have to kill, you could only disable as you did with Wealdwood. In doing so, you would increase our chances of survival significantly. A vow only binds a man if he wills it; the vows we make to ourselves are always the most tenuous, the most easily undone. If you decide that you will not fight beside me tomorrow, I will accept that you have honored a promise to yourself. I will think no less of you because you have put that commitment above and beyond my survival. But I know what I would prefer.”

“I’m not a fighter,” said Gaelwyn. “I don’t have any of the formal training that you or Vidre have.”

“You have as much as Dominic does,” said Welexi. “You have a body that any man would be envious of, even other illustrati of flesh. You have enhancement across all the physical domains, bones made thick and strong by the Bone Warden and skin made both tough and pliant by Charnel. You are not a fighter, but that does not preclude you from fighting. The only question is whether you will be beside me when we rush the castle.”

Gaelwyn was silent. The sun had risen, casting light on them. He could see the dark skin of Welexi’s face, a countenance that was noble and kind even in the worst of times. His thoughts turned again to the man that he would be without Welexi. If Welexi died, there would be simple, practical consequences. The vast network of bards and storytellers would collapse, both from a lack of central focus and a lack of funds. Gaelwyn would be barred from a number of kingdoms that had only allowed him in because the Sunhawk had given a firm declaration of trust. There would be no one to defend Gaelwyn from someone trying to make their name. But the biggest impact would be that Gaelwyn would lose his only true friend. Welexi wasn’t showing it, but the fact that he was asking showed that he was nervous about the outcome.

“Think on it,” said Welexi. “I’m going to wake Vidre up so she can have a shift as guard. I would suggest you get some sleep, whatever it is you choose.”

Once Vidre had stretched herself out and sat down just beside her makeshift tent, Gaelwyn laid down beside Welexi. Welexi was unconscious after only a moment had passed, one of the benefits of long experience in a number of wars. Gaelwyn was more slow to go to sleep. His head was too full of thoughts. If he waited until Welexi was in mortal danger, it might be too late. Even if he waited until just before the assault it might be too late. It was better to make the decision as early as possible.

Gaelwyn turned his focus inward, feeling the muscles beneath his skin. He began to think of how he would want to change, if he were going to fight. Some of it was theory, dreamed up long ago as an exercise in thought, tested only minimally to confirm that his thinking was sound. He began to alter his shape, just to imagine the fight better, going up against men with spears and swords, thick armor and illustrati powers. By the time he had finished his refinements, Gaelwyn’s mind had been made up.

#divider()

Vidre raced forward as the rubble fell, sprinting her way down the hillside and across the open valley to Castle Launtine. Her daggers were firmly locked into position on her thighs, giving her free hands to bat away the larger pieces of stone that fell from the air. The sound of the explosion was still echoing off the walls of the valley. If she pushed herself, Vidre could cover a mile in a single minute. The men and women who guarded Castle Launtine would still be trying to get their bearings by the time she got there. She spared a single quick glance behind her to make sure that Dominic was following. Whatever his other failings, he was sprinting along a few paces behind her, with Gaelwyn trailing after. There was a good chance that Dominic was going to die in the coming battle. A full minute of running across the valley towards the smoking castle was too much time to think on such things. Instead, Vidre put her focus forward.

An iron gate barred the way to the winding path that led up to the castle proper. Vidre approached it at speed, watching the guards running around as they tried to figure out what was going on. Anyone paying the slightest bit of attention would have seen the light Welexi had generated on the hill, which had a clear cause and effect with the explosion at the castle. These men wouldn’t have drilled for something like this. Even if they had, there was little that they could do.

An ordinary man with no standing wasn’t quite helpless against an illustrati. Vidre had sustained injuries in the past, some of them even as fresh as the day before. A two-handed sword or mace swung with full strength could potentially break a bone. A freshly sharpened sword could cut through skin, even if it wasn’t likely to bite too deeply into flesh. There was at least some element of danger from the common man, especially if he was properly trained. The guards on the ground showed some bravery at least; they leveled their pikes at her instead of turning to run.

Vidre used the full force of her weight to slam into the first guard she came across, narrowly dodging the sharp edge of the pike. She cracked his ribcage with a shoulder check, which helped to slow her down. Her daggers were in her hands in an instant. She continued forward, advancing on the next man. The guards wore breastplates and helmets, but their faces and necks were both exposed. Altogether there were half a dozen men on the ground, with another half dozen standing at the top of the gate or somewhere within it. The men had pikes, lowered so the head was pointing straight at her; it was easy enough to shove those aside, using enough force to send the weapon spinning and put its wielder off-balance. The trick to a fight like this was to keep awareness, so that at the same time she was stabbing upward into the soft spot at the underside of the jaw, she could also make sure that she would know if anyone was approaching her from behind. Her armor was thick enough to deflect or absorb any attack a pike could manage, but it was good practice all the same.

Vidre had given three of them mortal wounds by the time Dominic arrived. He moved forward to attack one of the men with pikes, striking hard enough with his sword of shadow to put a dent in the steel armor. Vidre paid only a small amount of attention to his part of the battle; he would serve as a distraction more than anything else. He could help to flank the illustrati that they were sure to meet, but he wasn’t their primary offensive weapon.

Vidre moved on to the next man, already impatient for Welexi to do his part.

#divider()

Calligae had set out toward Castle Launtine at first light.

The events of the previous day had rattled him, though he elected not to show it, even though he was alone on the road. He had been near the Ministry when the alarm had gone up; he’d rushed there as was his duty, taking the stairs three at a time and passing by younger men. There was a chance for glory here, but Calligae only gave brief thought to that. The truth was, he had crafted enough of an enduring legend for himself that he would retain his standing for the rest of his life, even if he disappeared. He wasn’t a young man anymore, trying to grab every scrap of renown that he could.

When he saw that it was Vidre in the hallway, he’d first thought that she had simply arrived before him. There was blood on her daggers though, accompanied by a manic look in her eyes. He’d thought he would get an explanation at least, but Vidre had never been one to monologue. He’d done what he could to drive her back, hoping that this wouldn’t be a fight to the death. It had been the upstart who had gone after Vidre like he was being guided by the hand of fate. There were too many new illustrati in Parance these days, young, hungry men and women who had carved away their own piece of the public imagination. Perhaps it was only his age, but Calligae felt there was something different in the character of them.

He had followed the illustrati of shadow out the window, trying his best to glide on the air or at least cushion his landing. He tended to think of other things while people were telling stories; he had no idea who the young man was, only that he was almost certainly going to be easier prey than Vidre was. Backed into a corner, Vidre would lash out with her knives, slicing cleanly through armor and flesh alike. The two had split their paths, which gave Calligae an opportunity to chose between them. If he’d been a younger man, he would have chased Vidre, thinking only of the story he could tell, even if that was the wrong choice.

He’d lost the young man, though not for lack of effort. When Calligae had made his way back to the Ministry of Legends, he’d gotten a number of shocks. The Minister of Legends lay dead, with his throat slit in his own office. Welexi had flown out a window. There were thirty dead at least, most of them Ministry soldiers, with no less than six illustrati among that number. The casualties were expected to rise as people succumbed to their wounds. Taken as a whole it was nearly unbelievable. For Vidre to take a turn towards villainy was almost expected. It often happened when an illustrati felt themselves beginning to fade. A hero falling from grace always got people talking, just as they would talk about a villain being redeemed. Vidre had enough unpleasantness lurking in her past that a fall could be anticipated. Welexi though, that was something else.

Calligae looked at the illustrati around him. He was right that they were young, but it was more than that. They carried themselves differently. They spoke of their kingdom with a zealotry that Calligae did not remember from his own youth. He’d noticed the changes that had been happening, but had dismissed his observations as being part of the way that old eyes looked at the young. It was more than simply that though. Many of the old faces had disappeared entirely, but he couldn’t recall the elaborate funerals or going away parties that illustrati demanded. Calligae hadn’t been paying enough attention to the world around him.

The Iron King would have answers, he was sure of it. The trip to Castle Launtine would provide some insights, one way or another, even if it was only by way of a polite rejection.

He was three miles away when he heard the thunderclap of an explosion.

#divider()

Dominic’s first strike hit the soldier’s armor. Dominic was mildly surprised that there was no parry to it; he had grown accustomed to sparring with Vidre and Welexi, who could easily turn away almost any attack. A pike wasn’t a parrying weapon, but Dominic had never really trained against it. He pulled back and swung his sword again, looking briefly into the soldier’s wide eyes. This blow hit the man’s neck with Dominic’s full strength behind it, cutting halfway through before striking bone. The man toppled to the side, taking Dominic’s sword of shadow with him. Dominic summoned a fresh one into his hand. When he turned to look for the next man, he saw that Vidre was killing the last of the guards. Not all were dead — some were on the ground, bleeding or crying out in pain — but they had been taken out.

Dominic saw the spray of dirt near his feet at the same moment he heard the gunshot. It had come from above, courtesy of a musket. The top of the gate had a handful of cannons, but the soldiers up there all had their muskets out. One of them took aim at Vidre, sighting his musket down at her and lighting the fuse. He was knocked backward as a spear of light stabbed through his chest; Welexi landed on top of the gate just afterward, fully clad in his armor of light from head to toe, covering his face and hands as well, so that no part of the man could be seen or struck.

“Come on,” said Vidre. “They didn’t have time to lock everything up.” She opened a door in the side of the gate, separate from the large portcullis that was meant for teams of horses. The door was iron, thick enough to take cannon fire, but it hadn’t been locked. Vidre was moving down the path by the time Dominic started after her. She didn’t look back towards him, nor did she glance at Welexi when he landed beside her.

They moved up the hill together, moving quickly. Every second that passed was another second for their enemy to regroup. Some number of them had surely died when the powder store exploded, but the castle itself had a thick iron frame. While there were now chunks of stone scattered on the ground, Dominic could see that the castle was still standing, at least when the smoke drifted away enough for him to see it. The day was eerily silent; Dominic had expected a flood of men to come rushing down from the castle to fight them, but beyond a few shouts he’d heard near the beginning and the screams of the men they’d killed at the gate, there was nothing.

Dominic wanted to run away. Killing that soldier had made him feel sick, a sensation only increased by the knowledge that he would have to do it again before the day was out. He’d watched Vidre and Welexi work together to kill from a distance, murdering men they only assumed were responsible for the assassinations. Attacking Castle Launtine smacked of story logic. Yet here Dominic was, trailing just behind as they rushed up the switchback path. If they arrived at the castle and found it empty, or filled only with functionaries and bureaucrats, what would they do then? Or worse, if the Iron King was not truly dead but only insensate, and every action they’d seen had been taken on his behalf? Dominic felt certain that no matter what they found, justice via bloodshed was what would follow.

Welexi strode forward with his spear in hand. He had a commanding presence that was only heightened by the blood on his armor. When Dominic watched him, all the objections began to wash away; how could a man with chin held so high and back kept so straight be anything but right? Then Dominic would remember the moments of petulance and childishness. He remembered what Vidre had said, about Welexi having her do the dirty work so he wouldn’t have to feel the taint of it. It felt as though the glory of the man should fade, as though, once the flaws of his character had been revealed, there should be something in his appearance that belied the undercurrent. Yet there was not. Welexi was firm and tall, the very picture of a hero.

#divider()

The winding path up to Castle Launtine stopped at a large courtyard. Vidre had been to the castle a number of times before, and the courtyard had always been one of her favorite places. It was filled with a variety of plants from around the Iron Kingdom, artfully arranged so that a person could take a walking tour through the botany of the kingdom. Castle Launtine lay at the heart of the Iron Kingdom. While it had once been a purely defensive structure, the Iron King’s rule had seen it transformed into an enormous home, both a symbol of his everlasting power and the diplomatic heart of the country, ministries aside. The thick oak doors of the castle were normally opened wide, the better to take shipments of iron which the king produced on a daily basis while holding meetings or dictating to his assistants. The major defensive features of the castle faced downhill, the expected angle of attack. While the central doors from the courtyard could be barred, the castle still had its windows. That was how Vidre planned to get in.

When she rounded the final corner though, the castle doors were standing wide open. Her first instinct told her that this was a blatant trap, but then she saw the people. They were bleeding and hobbling out the front doors, or laying down in the manicured grass. It had only been a handful of minutes since the powder store had exploded, but in that time the courtyard had started to be turned into a makeshift triage center. Vidre had expected soldiers ready and waiting, illustrati armed and armored to the teeth with any number of domains, but there was nothing.

Vidre scanned the faces, unwilling to move forward. They were spotted quickly, but the reaction wasn’t what she had expected either; no one was running away or screaming, they were only standing and watching. More people were coming from inside the castle as she watched.

“They weren’t ready for us,” said Dominic. He kept his voice low. “They’re not combatants.”

Vidre felt sickness rising up in her. They had blown the gunpowder store thinking that they might be able to kill a good number of people within the castle. It had all the gunpowder that the castle needed to fill dozens of cannons over a lengthy siege. If they had done nothing more than kill civilians, or soldiers who had done nothing wrong aside from choosing a safe posting …

When the first illustrati leaped down from the battlements to land in the courtyard, Vidre breathed a sigh of relief. She was armored in glass from head to toe, but didn’t move in it anywhere near as smoothly as Vidre did. To Vidre, the glass could cling like silk, molding itself to her skin when it didn’t need to be hard. This other woman had clearly spent time crafting her pieces of armor, quite inexpertly. Other illustrati followed behind her, taking the thirty foot drop with ease. When six had dropped down, Vidre thought perhaps it would be a difficult battle. When another four followed, the odds looked a little more bleak.

There were limits on how powerful the conspiracy could possibly be. The number of illustrati within the Iron Kingdom was finite. Up until yesterday, they’d been operating in secrecy, keeping both the masses and the illustrati unaware of their existence. If they were culling from within the Iron Kingdom, how many illustrati could they really have robbed of their power in the last year? Dozens, easily, but only from among the lower ranks. Taking one of the true legends, rather than the village champions, would have caused a stir.

When another six illustrati came through the thick double doors that led into the castle, Vidre smiled. Sixteen against three was even worse odds than before, but her nightmare from last night had been that she would be facing down a single man with ten times her strength and access to every domain. She’d been spared that, at least, if they were dividing power among so many people.

Beside her, Gaelwyn began to take off his shirt. It was unusual for him to follow so closely into battle, where he would be a liability more than an asset. He revealed hard, bulging muscles that Vidre could sometimes forget belonged to the small, unassuming man. He had small red welts just beneath his collar bone that Vidre had never seen before. When his shirt fell to the ground, Vidre saw long red ropes fall into his hands. They were lengths of raw muscle, with no skin covering them. They attached at his wrist, protruding from a cut in the skin. In form they reminded Vidre vaguely of tentacles or tongues. The sight was sickening, but it meant that after such a long time, Gaelwyn meant to fight.

“We need to attack now, before they can get into formation,” said Vidre. The people in the courtyard were still standing around, mostly looking shocked or confused. Welexi gave a brief nod, which was all that Vidre needed in order to start moving forward.

“Hold!” shouted one of the illustrati. He was wrapped in copper armor, more functional than aesthetically pleasing. “You come to attack us without any attempt at parlay?”

“You lost the right to speak with us the first time you attacked,” said Vidre. She didn’t slow down. “The second attempt ensured that you would be hunted down, and the third —” she broke into a sprint “— ensured you’d die slowly!” The words rolled of her tongue easily. Her glass helm slammed down into place, covering the last inch of her body. Vidre leapt through the air, singling out a man with no faceplate. He tried to turn and move, but she hadn’t focused on him until the last moment. He reached up with bare hands, likely an illustrati of one of the bodily domains trying to find purchase. He wasn’t quick enough to block the blow, only to knock it off course. Vidre’s dagger slashed his face, cutting through one eye across his nose. He screamed and lost focus, which was enough to leave him undefended for the second attack. Vidre was hit hard in her back, shattering the large piece of glass there before she could confirm the kill.

She flipped over and lashed out with a lazy swing; the illustrati had converged on her, almost half of them coming to the defense of the man she’d just killed. The one who’d hit her so hard was a large man with a great maul. Vidre did her best to repair the cracks while preparing to roll out of the way of his strike, only to find her arms and legs had been grabbed. She kicked and cursed, growing out shards to slice uselessly at gauntlets. Her back was in agony from the hit. The large man swung his maul up into the air, ready to bring it down for another hit, but before he could, a spear of light erupted from the front of his chest.

Welexi had left his face exposed, which allowed Vidre to see the same calm dispassion that the Sunhawk normally carried into battle. He had a spear in either hand; he spun them around lazily before darting forward to drive the people holding Vidre back. Vidre scrambled to her feet, feeling a sharp pain in her back, but she could still move. The illustrati they were fighting weren’t rank amateurs, but they weren’t at the peak of standing, nor were they confident, trained fighters. There were simply more of them. As the moments passed and the pain in Vidre’s back began to grow, the illustrati spread out around them. Her attempts at intimidation and the murder of two of their compatriots hadn’t broken them, but it was only a matter of time. The fight would be won long before they’d dropped down to even odds.

Dominic had entered the fray only belatedly; he was fighting two illustrati of his own and doing a poor job of it. Vidre rushed to defend him, but there was a small moment of hesitation. Dominic wasn’t telling her the full truth of what had happened at Hartwain’s. She’d felt it when she’d seen him leave her manor. She’d felt it even more strongly when they’d met back up afterward. She had become sure of it when he’d waited until quite late to share vital information. Something was off about Dominic, enough that she’d been keeping her eye on him for quite some time. She went to go save his life all the same.

#divider()

Dominic held his sword in front him, trying to keep his eyes on the two illustrati coming towards him. They split off from each other, moving to flank him. Welexi rushed past, going to Vidre’s aid, but that left Dominic alone. His sword wavered in front of him, switching back and forth between the two men. Dominic tried to remember all the rules that Vidre had drilled into him over the weeks, knowing that it probably wasn’t going to be enough. The smart thing to do would be to run away. Dominic held a defensive stance instead, hoping that he would be equal to these opponents. Their domains weren’t obvious; both wore full plate armor and held long swords, but they had none of the markings of their domain that Dominic had come to expect from illustrati. None of the useful materials then, probably not the metallic domains, and keeping in mind that each of them might have more than one —

The one on the left attacked with a long, sweeping strike that Dominic easily dodged. The other came in low, swinging for Dominic’s feet. He took the blow on his armor, feeling the sting of it. Dominic backed up, trying to keep the two men from flanking him completely. He pulled the shadows around him, plunging himself into total darkness, but from the movements of the two men, this wasn’t enough to give them pause. Both their heads seemed to track where Dominic moved, at least so far as he could see from the way the shadows moved. Dominic dropped the shadows back down soon after, hoping that Vidre or Welexi would see.

Dominic had made his armor as strong as possible and wrapped it around himself so that it was sealed against the prying hands of someone using the bodily domains. He’d done training exercises with Vidre that would help him to survive without air for a few breaths, but he had little confidence in his ability to fight while doing that. He kept backing up as the illustrati approached him. Both moved forward again, attacking at once. Dominic parried one attack, which brought electric blue sparks from the sword, but the other attack slipped through, striking him in the armor. Vidre had once said that most battles between armored enemies came down to who wore down more quickly rather than hard strikes. If that were true, fighting against two men would doom Dominic to a slow death.

Both men attacked again; they’d managed to flank him, which left him waving his sword around trying to defend against both of them and taking strong hits to his armor. The armor made it hurt less than it might have, but it was hardly an absolute defense. Each strike brought pain with it, enough that he knew he’d be bruised all over if he survived the day.

The one to Dominic’s right was kicked aside by a blur of sharp glass. Dominic turned his attention to the other, who had fully electrified his sword. Dominic had been warned that a solid strike of lightning could cause muscles to spasm and tense, but he’d felt no effects from it thus far. Shadow seemed to stop the effect entirely.

Vidre came to Dominic’s side. Her daggers were dripping with blood. She hissed slightly, then moved forward, taking a blow that shattered the glass of her bracer before quickly reforming. The man’s full helm had small holes to allow him to breathe. Vidre slammed her dagger against it, then held her hand there as he tried to push her off. Dominic moved forward and grabbed the man’s sword hand, twisting it around and pinning it behind the man’s back. Vidre stepped away after only a few seconds, satisfied with her work. She swept the illustrati’s leg from beneath him, with the dagger still stuck in his helm. Dominic watched for a moment. The illustrati hadn’t been killed; he was struggling, trying to free himself from the helm, but glass had fused shut the hinges and clasps that would let him escape.

“He won’t last long,” said Vidre. She turned toward where Welexi was fighting a desperate battle against six men and women. Vidre started forward, then stopped short. Gaelwyn was on the move and she seemed intent on watching him.

The ropes in Gaelwyn’s hands were flesh. He swung one above his head, letting several yards of red muscle extend to their fullest. When he reached the melee, he slipped the tentacle forward. It struck one of the illustrati on the back; he fell down instantly, dropping his weapon. The second man went down as quickly as the first. The third ducked beneath the length of muscle, slicing it with his sword, but he was struck in the helm by something pink and fleshy that had come from Gaelwyn’s chest. Dominic watched in shock. Gaelwyn was famous enough not to be limited in the same way that other illustrati of flesh were. He didn’t need to touch anyone skin to skin, he could reach straight past their armor. Gaelwyn had added onto the range his physical touch allowed.

The fight was over. Dominic stripped the shadows back from around his face. He breathed in air that tasted too much of metal in long, ragged gasps. Vidre was doing much the same, but she was using her energy to move forward, to where Welexi stood with his hand on Gaelwyn’s shoulder. He was smiling at the doctor, speaking soft words of encouragement.

“We need to keep moving,” she said. “I count eleven bodies, that means five in retreat.”

“It might have been prudent to parlay,” said Welexi.

“And waste the element of surprise? And lose the element of terror as well?” asked Vidre. She shook her head. “I have no regrets.”

“There is more to do here,” said Welexi. “Artifacts to find and leaders to question.” He turned to Vidre. “Try not to kill the last person who knows what we wanted to find out. The man who wore copper had the domain of fire as well as his metal. We’re close to them. They have the much-vaunted ability they’re said to have.”

“That doesn’t make sense,” said Vidre. Her eyes scanned the battlements of the castle as well as the window as she tried to catch her breath. She was holding her back with one hand. “A single man with all their combined powers would have been more of a threat. I’m grateful they split their power in separate bodies, but … are they restricted to only two to a person? I’m sure some of those men had only a single domain.”

“They don’t want to concentrate power,” said Dominic. “They don’t want a monolithic figure in charge.”

Vidre stared at him. She seemed ready to say something, then turned away. “Perhaps you’re right. Come on, let’s go. No sense giving them too much time to set traps.”