#import "/funcs.typ": *

#appendix("Appendix: On the Nature of the Domains")

In _Meditations_, the earliest work of its kind, Lyander first divides the domains into two groups: material and immaterial. At first this might seem wise, in the ways of the old masters, but the problems are immediate, even at that first division. If we believe that there is a domain of fire, as Lyander did, where do we imagine that Lyander would have placed it? There are arguments to be made either way, none of them definitive. There is a little-known tract issued forth by Lyander which attempts to clarify the definitions he makes, to draw lines in the sand so that none could argue, but of course this weakens his system immensely, which is the reason that printings of _Meditations_ so rarely include that tract. Lyander concludes that fire is immaterial, while notably stating that rust is clearly material. Alchemists now know that both are part of the same process, which would seem to invalidate his reasoning.

Other, more modern systems are fraught with their own difficulties. It has of late become fashionable to use Herrus’ system, which divides the domains into elemental, organic, bodily, ephemeral, manufactured, metallic, and animistic, with derived elemental sometimes included as an eighth grouping or bodily folded into organic to arrive at six groups (of special significance to the people of the Southern Plains). Herrus contends that this system of groupings is descriptive; he has placed them such that like domains are next to each other. Variants on his arrangement move the pieces around, but they only serve to make clear the fact that the groupings are arbitrary. Given the failures of Lyander and others, we have moved from believing that we might find a True Structure to accepting that there is a Convenient Structure which is useful despite not being wholly correct.

Here I will attempt something different; an examination of the domains as they exist, along with a hypothesis as to their nature, one which we might arrive at through the strength of analysis alone

#subheader[Domains]

To start, we must define what we mean by a domain. In the broadest sense, a domain is:

1.  A set of abilities a person possesses, which increase with fame.
2.  A set of things on which those abilities may act

Lyander’s classification of abilities has fared much better than his attempted classification of domains, and though we might quibble, I do not believe there is one better. I will endeavor to be exhaustive here; the more learned among my readers may wish to skip ahead, for I believe I say nothing that offers sufficiently new illumination of this subject.

#v(0.5em)
_domain genesis:_ the ability to create more of a domain
#v(0.5em)

Things get tricky right from the start. When referring to the material domains, it is clear what we mean when we say “more”; two pounds of iron is more than one pound of iron. Yet there are what we might call process domains, which are usually split between ephemeral and elemental. What does it mean when we say “more” sound? Sound is composed of waves, so we might say that in that case, domain genesis is the creation of a sound. Yet what of fire? We know that fire is a process, a reaction which occurs. In that case we sometimes say that domain genesis is merely the _beginning_ of a process.

There are two other prominent exceptions in addition to this duality of process domains and material domains; heat and cold. These together form a third group, which we might refer to as the state domains. What does it mean to create more heat? It means only to change the state of an object. But we have just said above that a domain is the set of things upon which those abilities act! If the domain of heat can affect the property of any object, what does that mean? I hope to one day have a better answer, but as yet I have none.

Genesis follows several rules, though whether those rules illuminate something important about the nature of the domains is as yet unclear.

- It is easier to create a material which is simple rather than complex. Creating a pound of flesh is much slower than creating a pound of stone.
- Speed appears to depend largely on mass, rather than volume. A pound of gold and a pound of copper are equally complex, but would take the same amount of time.
- It is far easier to create from an existing source. An illustrati of water fully immersed in his domain will be able to create a gallon of water much faster than one stuck in a desert. For this reason it is common for illustrati to be locked away without access to their domain, where possible, and for _that_ reason it is common for illustrati to hide small slivers of their domain about their person.
- A powerful enough illustrati can make more of their domain from nothing. It is unclear whether this is simply a function of raw power, as Bellsthwill suggests, or whether there this is a function of there being unavoidable contaminants in supposedly sterile environments which we cannot yet detect.
- The animal domains have thus far proven incapable of domain genesis.

#v(0.5em)
_domain kinesis:_ the ability to move a domain
#v(0.5em)

At first blush this ability is simple. The apple is often used as a stand-in when teaching about the domains, so we imagine the illustrati moving that apple using an unseen force which responds to their will. When we speak of range extension, we can imagine an illustrati touching one apple, then causing a second apple which the first is touching to move.

Apples were chosen because there is an orchard close to the Kellos Summit where many of the early scholars had the first discussions of what we might imagine about the domains. However, as I hope I have said clearly enough above, there are non-trivial differences between the domains. The physical aspects of being able to move a piece of iron do not properly map to some of the other domains.

There is an interesting study to be made in the domain of heat. Heat was always a troublesome domain for those who had it, because while it was fearsome in its own right if let loose, the process of cooling back down was quite slow. Heat did not, of course, harm the illustrati, but it made a large number of things very difficult for them, mostly in regards to interacting with anything made of a flammable material or even another person. A hundred years ago, Calor the Bold, the third man to carry that name, came to understand how to move heat.

He began by looking at how this phenomenon called heat behaved, much in the way that I now look at the phenomenon of the domains. He noted that when a hot object is placed next to a cold one, the hot object transfers its heat. This is a rather facile observation, but he asked a question that must have been asked relatively few times before. If movement was one of the domain abilities and the property of heat could move, why was the domain of heat as experienced incapable of that movements? The answer was that it _was_ possible, though this movement is far different from the others. Calor provided descriptions of how to properly conceptualize this technique, which is now used by illustrati of heat the world over.

Domain kinesis is likely the mechanism by which a few domains are capable of creating the so-called “solid ephemerals”; because kinesis is an unseen force which acts on the domain, it might be that the solid ephemeral merely acts as a vessel through which to apply that unseen force.

#v(0.5em)
_domain alteration:_ the ability to change a domain
#v(0.5em)

Alteration is one of the less understood of the abilities. It is also one which is varies widely from domain to domain. The key piece of understanding that brings unity to this ability is that most domains do not have a singular focus. There will be more to say on this later, but a domain can encompass many different things; the domain of stone includes onyx and marble, for example. Domain alteration is then the changing a domain material into another domain material that is nevertheless within the same domain. Curiously, some of the domains appear to be entirely singular and thus have no access to domain alteration.

#v(0.5em)
_domain immunity:_ the passive ability to prevent personal injury from a domain
#v(0.5em)

It has often been remarked that without immunity, many of the domains would be useless. The ability to light anything on fire with a touch would quickly result in serious burns; being able to scream loudly would quickly make a person deaf. It has been suggested by those who favor a Creator that this is a matter of necessary protection, but I think that this is unlikely. Domain immunity applies to every domain, even those which hold no natural danger to their users. An illustrati of iron cannot be pierced or cut by iron, but we can hardly say that he would be useless without this ability.

As with most abilities, this one scales with standing. Someone with negligible standing will have no protections, while a middling illustrati would take a reduced hit; a sharpened dagger of glass might bite into the skin as though it was blunt rather than sharp, for example. Because of this, illustrati must be careful, especially the minor illustrati. An illustrati typically cannot push his domain so far that he will hurt himself, but it is well possible for an illustrati of flame to start a fire which grows beyond the protections conferred to him.

The homeostasis provided by domain immunity is not complete, nor is it uniform among the domains. Illustrati of water are able to breathe beneath the waves, but an illustrati of wood with a branch shoved down his throat would not. Immunity protects against most attacks which might be made with a weapon of that domain. When the phenomenon is closely observed in controlled conditions, as was done by Pynthos, it appears to follow naturally from the other abilities. We might think of a sword stabbing into the belly of an illustrati of iron as undergoing a subconscious version of domain kinesis. This notably continues to function even in situations where the illustrati is not aware of the threat, as well as when the illustrati is simply unconscious, and indeed even when the illustrati has been rendered insensate through methods such as lobotomy.

#v(0.5em)
_domain intuition:_ the ability to understand a domain
#v(0.5em)

Of all the abilities, domain intuition is the most philosophically troubling. It would very much appear that there is something different within the minds of the illustrati which allows them to use their abilities in full. I have seen illustrati of water make sinuous whips without any apparent thought given to the matter. I have heard tales of illustrati making a sword of shadow with no training or formal education. We have examples of annealed and quenched metals from long before those techniques were in common use.

The intuitions are as varied as the domains themselves. Illustrati of steel have been able to forge far better weapons than even the greatest of blacksmiths, not just because of their control of the material, but through an intuition about what makes a metal hold its sharpness. Illustrati of flesh are able to fix complicated flesh wounds without having to know or even understand how the individual muscle fibers connect to each other. Intuition offers information which is sometimes unknown to humanity, which offers us a window into what might be possible as we expand the scope of true understanding.

Yet we must also look to cases like Calor’s, where a capability was _uncovered_ through experimentation and knowledge. I have said that an illustrati of iron is more capable than the greatest blacksmith, but if an illustrati of iron learns smithing he can become more capable than his compatriot who remains ignorant. Why are certain things intuitive to illustrati and while others are not? We do not know, and I am not so satisfied by any of the explanations on offer that I feel the need to reprint them here.

#v(0.5em)
_domain sense:_ the ability to sense a domain
#v(0.5em)

Domain sense takes many different forms. While ophthalmoception (the visual sense) is the most common, I have found numerous examples of extension into the other senses as well. Of particular note is proprioception, which seems nearly as common as ophthalmoception; a illustrati touching a material of their domain can often feel it as an extension of the self. I have done tests with a willing subject, a young woman with the domain of copper named Quiver, whose only condition was that I mention her by name in any publication which featured the research we performed together. She was able to accurately describe several different images stamped onto copper plates with only a finger touching the material.

A better understanding of domain sense might regrettably be had from the foul experiments of the Iron Kingdom. It was commonly known that the visual sense did not strictly depend upon the eyes, given that illustrati maintained their sense even with their eyes closed. The experiment done by the misbegotten surgeons of the Iron Kingdom was to progressively blind an illustrati in increasingly damaging ways in order to find when the domain sense would be lost. Even after the entirety of the eyeball was destroyed, domain sense verifiably remained. It was not until the optic nerve was destroyed that ophthalmoception was verifiably destroyed. What this result might mean is anyone’s guess, though more ethical modes of experimentation which specifically investigate the nervous system seem promising.

#v(0.5em)
_domain form:_ the ability to take on aspects of the domain
#v(0.5em)

I have so far been silent on the animal domains, but they must now be given their due. Domain form has thus far been shown to exist only within the animal domains, though it has long been predicted that it is somehow possible for other domains as well, in the same way that Calor proved heat capable of movement through diligent study. Domain form is characterized by a shift in physiology, usually subtle, towards being similar to an animal in question. This process is directed by the illustrati, usually so that the changes are cosmetic in nature. The benefits of this transition tend to be minor and depend almost entirely on the domain. More radical changes are often accompanied by changes in diet. I have heard it said that there are changes in cognition as well, though verifiable evidence for this is lacking. As always, we must be wary of motivated misinformation.

It is important to note that domain prostheses is something different entirely. An illustrati might forge an arm of gold to replace one which he has lost, but while he might, through practice, be able to move this arm as though it were one of flesh and blood, this is simply a combination of domain sense and domain kinesis, not an example of domain form. Domain form has an element of transformation to it which prosthesis lacks.

#subheader[Internal Sensations]

Based on the interviews I have conducted, the illustrati themselves do not feel much of a distinction between these classifications of their abilities. That is to say, an illustrati of iron of course understands that there is a difference between moving a piece of iron and changing the shape of that piece of iron, but to him these “feel” as though they are quite similar actions rather than being modal. It is therefore difficult to claim that any classification of abilities is legitimately useful; it might be that with a better understanding of the mechanisms involved, we would come to the realization that they are all part of a singular whole, which appears to be how the illustrati perceive it.

One central question that has appeared through the ages has been whether the domains are singular or faceted. If Able and Beth are both illustrati of water with equal amounts of standing, will they necessarily have access to all of the same abilities? Or might it be the case that Able would be capable of some things which Beth is not? I believe that this confusion to be incidentally created by the illustrati as part of their strategies in the pursuit of standing; every interview I have conducted and every trustworthy primary source I have read has indicated that all illustrati of a given domain are equal in their abilities. Oh, some might have trained themselves more in some specific discipline, or they might know some trick which they arrive at through either training or deep knowledge, but I have found no evidence that these aberrant behaviors could not in principle be obtained by others. The seeming differences between illustrati seem to stem mostly from their need to appear distinct in order to raise their standing.

#subheader[A Theory On The Makeup of the Domains]

The question we must now come to, having described the domains, is the central question of _why some things are domains and others are not_.

The first prong of my theory is simply a variant on Lyander’s formulation. Where he said that the domains are all vital to humanity, I will instead say that all of the domains are _compelling_ to humanity. There are ten animal domains. Of those, six (feline, canine, avian, piscene, equine, and ruminants) are either domesticated animals or, in the case of fish, a nearly universal source of food. Lyander believed wholeheartedly in a Creator, and beyond that, a Creator which held humans to be paramount, so he viewed the domains through that lens. Yet there are domains which fit poorly with Lyander’s idea of vitality, such as the domain of lava, which has not once been vital to humanity no matter what Lyander’s supporters say.

When we look across all the domains, we can see that each of them is compelling to the human race in one way or another. There is nowhere that this is more clear than in the metallic domains. Tin and brass are both domains, though brass is an alloy of tin and zinc, and zinc is not a domain. Why? There have been many answers to this question, but with the discovery of zinc in its pure, irreducible form, I believe we must raise an eyebrow at those who claim that the domains are somehow basic to the world.

There is another word I might use instead of compelling: famous. The domains themselves have their own variety of standing which is distinct from the notion of standing as applied to humans. The only question which remains is the question of how this “domain standing” might function.

So far as we can tell, the distribution of the domains is in exact proportion to the number of domains. In every instance we can find where a random sampling of the population was available, we saw no domains which were more likely than others. If our sampling is not random, such as a sampling of illustrati rather than the general public, we find much more of the “useful” domains, those which offer superior manufacturing, superior combat ability, or have some other aspect which creates the virtuous cycle of utility increasing fame and fame increasing utility.

Yet this still leaves us with some of the perennial questions about the domains. We might easily imagine that brass has passed some threshold of human interest which zinc has not, but why are the divisions where they are? Why is there not a domain for simply “metal” instead of the variety of metallic domains we see? Why not simply a domain of “animals”? We know that domains can include many things which are sufficiently similar. On that point, why is there a domain for “stone” instead of a dozen stone domains, which might include volcanic rocks, sandstone, limestone, and so on? Why is the domain of wood not split into birch, oak, and so on? Why are there distinct domains for so many animals, yet for humans there is instead a number of bodily domains which do not fully encapsulate the entirety of the raw materials which make up a human?

Let me explain the second prong of the notoriety magnitude theory of domains by way of a set of observations and a set of predictions.

Whether the domains are static or variable is, unfortunately, a matter of historical record. Sadly, written records are rife with unreliable legends which the illustrati understandably propagate in order to increase their own standing. We must treat any historical reports of new domains as extremely suspect. As just one example, a shaman named Al-Shira from the Patrean islands claimed to have the domain of life, which allowed him to kill with a touch and bring the dead back to the realm of the living. His repeated excuses for why he could not bring the Patrean queen back to life led to him being executed by the Patrean king. I have seen more credulous historical scholars accept this account as being true, but singular instances of domains do not fit within any extant framework, nor do we have any rigorously studied examples. We cannot trust individual accounts, but I believe we _can_ trust broader trends.

Steel has been known for all of recorded history, from back until the times of the first post-Harbinger civilizations. In many cultures, however, there was a strong implication that steel was something which only illustrati could make; in Garrund, steel is still called _simo sidero_, which roughly translates to _fame iron_. It would appear that there was a period of time during which steel was exclusively (or at least primarily) produced by illustrati, up until roughly five hundred years ago, until better bloomeries and crucibles brought steel production into the realm of the mundane. At that point, steel moved from being a tool of the elite to something much more common. It is then that I believe we see a fairly clear split. The century before then, there is no note made of illustrati of iron being unable to create steel. A century after, this distinction is common. I believe what happened is that iron and steel were once the same domain and following the proliferation of steel, the domains were split in two.

The theory does not rest on any specific piece of evidence though; there are many examples we might give. Though we have long thought of cats as being a staple animal domain, there is no evidence for anyone having held the domain of cats prior to six hundred years ago, at roughly the time they were imported to the civilized world and began their madcap proliferation. I have heard it remarked that _of course_ someone could not have a domain if none of the domain animal was present, but I find that theory to be dubious given a few historical examples of illustrati who never exhibited control over any domain. Furthermore, we would expect that if the feline domain only depended upon the presence of felines, we might find some illustrati among the natives who were noted for their command of said animals. Though their records are woefully incomplete and subject to much the same unfortunate pressures as our own, neither I nor my colleagues in occidental studies have uncovered anything of the sort.

Yet it would be easy enough for even a rigorous scholar to pick and choose the pieces of our fragmentary, unreliable history in order to make a compelling argument for any one particular theory. Instead I shall endeavor to do something much more difficult and far more reliable as an indicator of my correctness; I shall make a prediction. There are three predictions which my magnitude theory of domains might make. The first is that a domain might split in two, as I believe iron and steel did at some point in the past. There are no domains which I think are particularly ripe for this, whether because the domain contains two concepts which are distinct from each other, or because there is some ongoing shift in perception. The second is that two domains might collapse into a single one, or a domain might evaporate entirely. There is little historical evidence for this ever having happened, so I cannot speculate on whether it might happen again. Lastly, a domain might form from whole cloth. This, I believe, is the most likely scenario, so here I will stake my reputation. We know that the world is changing. We are in an era of unprecedented progress. There is one element to this progress which I believe is ripe to become a domain of the illustrati; gunpowder.

Gunpower has already changed the face of war. A well-aimed pistol can threaten all but the most powerful of illustrati, and I have heard of none for whom it would not result in injury, even if that injury is minor. All across the civilized world, the gun is becoming a symbol in its own right, transformed from a tool into an icon. For this reason I predict that the next change we will see to our map of the domains will be the addition of gunpowder.

#subheader[Conclusion]

Where I have held close to the established schools of thought, I hope that I have provided a useful overview for those with only passing familiarity with our study. Where I have made novel arguments, I hope that I have proven persuasive. Yet if there were one thing I should hope that the reader will take away from this tract, it is that we can only approach the subject of the illustrati to the extent we have reliable knowledge with which to do so. Too many of my colleagues have based their thoughts on stories which have no foundation in reality; the same mindfulness of ways and means which now marks so many fields of human endeavor must thrust its way into the last bastion of legend and superstition.