#import "/funcs.typ": *

#appendix("Appendix: On the Nature of Standing")

It is now widely know that fame and infamy correlate to extraordinary abilities, but this knowledge was not always so firm and entrenched, especially among uncivilized people. The Djamila believed that their _fadi_ were granted their powers through spirits. When someone started to become stronger or faster, they would say that a spirit had inhabited them in order to lend them strength or lead them down a dark path. The existence of domain abilities lent some credence to this conceptualization, because the Djamila would conceive of a man wielding fire as being possessed by a fire spirit. I have heard even educated people ridicule the Djamila for these beliefs, but I don’t find their reasoning so implausible. If we started from a position of ignorance, we might come up with something similar.

The primary difference between the spiritual theory of power and the fame theory of power is in the predictive power that they allow. The Djamila had explanations for every fluctuation in power, just as we do. If a leader’s power began to wax, they would say that the spirit had set its roots into him. If a musician’s power were waning, they would say that he and the spirit were out of harmony. Someone from Gennaro would instead explain these changes as resulting from a change in standing, which to most people seems as natural and comfortable as the explanation of the Djamilian must have seemed to him. Yet our hypothetical musician who finds himself with waning power would behave much differently depending on which of these two theories he believed; he would either commune with the spirits, or try to bring relevance to himself. One course of action would be correct and the other would not. That is the essential importance of determining the truth behind theory. There are many explanations for natural phenomenon — I do not mean to pick on the Djamila — but only one explanation has the distinction of being correct.

The intent of this tract is to drill down into that nebulous concept of standing, which most people equate to fame and infamy. While the difference between the Djamilian “spirit theory” and the more modern “fame theory” is large, when looked at up close the “fame theory” must be broken down into a multitude of smaller, often competing theories, each with their own differences, which we must look at through a similarly lens. Though these differences are not so large as those between the theory of spirits and the theory of fame, they are of utmost importance for any illustrati seeking to maximize their own abilities.

#subheader[What is standing?]

“Standing” is a shorthand. In the modern day it is imagined as a pure number, one which goes higher or lower. Higher standing means more in the way of abilities, while lower standing means less. The original conception of standing as laid out in _Elevations of the Illustrati_ had standing as a system of *absolute* rank, such that every person in the world might be given their own unique number and no individual could advance unless it was at the expense of another. If we could agree that there was one man who was the most famous in the world, then perhaps it wasn’t so absurd to think that this distinction was, itself, meaningful. The idea of rank is entirely without scientific backing though; _Elevations_ suffered greatly from the culture in which it was written, where systems of ranking were vital to the concept of castes.

The modern conceptualization of standing is best captured by the scholar Jamesh, who likened it to water. Every person has their own cup, and these cups can be filled equally or disproportionately. “Standing” is then something immaterial which someone can have more or less of. Jamesh was silent on the matter of what “water” truly was in this analogy, with no answers as to whether it could be created or destroyed, or merely redistributed. Given some of his other scholarship, this sparsity of thought is unsurprising. Still, it is the foundation from which modern theories all spring.

I have heard it suggested from some lay people — neither scholars nor illustrati — that standing could simply be expressed as “the number of people who know your name”. This is wrong for trivially obvious reasons. First and foremost, there are illustrati who operate under pseudonyms, and while standing is notoriously difficult to track, there are a handful of illustrati who operate under _multiple_ pseudonyms, and whose given names are entirely unknown. If they suffer for this, it is not apparent in their abilities. Molkowai, in particular, uses a different pseudonym on each continent, and despite that is considered one of the most powerful illustrati in the world. The simplest explanation is that names matter very little.

Another popular theory is that standing is, in some respects, a measure of deeds and their impacts. The obvious problem with this is, naturally, that attention and knowledge do appear to increase standing. The modified form of the theory (which predates modern fame theory) is that standing is a result of collective psychic beliefs about deeds and their impacts. This is a rather different claim, but also wrong; there are illustrati who have a demonstrably large amount of standing despite doing nothing, and through history there have been a number of illustrati whose deeds have been revealed as pure fabrications — and in point of fact, such revelations typically cause standing to increase, at least in the short term, rather than evaporate entirely. The most egregious example is probably that of the illustrati Austius, who falsely claimed to have reached a new continent, and was disproven five years later, which only caused his standing to increase.

If “impact theory” holds that illustrati gain their powers through concrete actions, and “perceived impact theory” holds that illustrati gain their powers through what’s perceived to be true, then what are we left with when both these appear to be false? We might excise the ‘impact’ portion of perceived impact theory altogether, leaving us with perception alone, a concise thesis of which might be, “illustrati gain their powers through being perceived”. This matches somewhat to the tendency of the more successful illustrati to wander about, stopping for days or weeks in various ports of call as they continue on their circuit, but as stated before, we cannot take the illustrati for definitive masters, nor can we take the established way of doing things as the best way.

If “perception theory” were true though, what would it mean and what would it imply? First, it seems obvious that we must take “perception” in the broadest possible sense, including stories told secondhand, since there are illustrati who never leave their city of birth and nevertheless accrue enormous power, indicative of very high standing (Xolo, Peritus, and Gelgar would be the best examples). Second, it’s clear that “perception” might only be a proxy. If it were true that perception and perception alone mattered, then when songs were no longer sung and stories were no longer told, an illustrati’s power would fade completely. Though this is a difficult thing to investigate (as are all powers of the illustrati), that does not appear to be the case in a few examples; attempts have been made to curtail the legends of problematic illustrati, and while these attempts often backfire, in a few cases they have appeared successful. Even in those successful instances, the illustrati appears to retain some amount of power, even if it is diminished.

This brings us then to the next evolution of “perception theory”, which is shorthanded as “thought theory”. While it’s often called “fame theory” by the laymen, that’s actually a subset of “thought theory”, though it is the most widely accepted one. According to the scholar Kinshew, in his seminal work titled simply _Meme,_ we might consider that illustrati gain their power through the amount and strength that people think of them. This maps most closely to our observations of how illustrati gain their power, and most of the more popular theories that fall under “thought theory”, including Kinshew’s own, make additional assumptions that are without sufficient evidence or experimental data to confirm.

#subheader[Competing and Expanded Theories]

- Kinshew’s “meme” theory coins a term, “meme”, used by him to refer to any concept which “lives” inside the head of a person. These “memes” can be transmitted from person to person, growing and mutating along the way, and subject to competition with each other, for a person only has time for so many thoughts, and only room for so many memories. Kinshew then constructs a metric that he calls “memetic strength”, which appears to be a proxy for emotional and intellectual strength and frequency of thought. None of this has been verified through experimentation, nor is it possible to do so through currently available means. Nevertheless, “meme theory” is the most popular theory amongst academia.
- Once an old standby, “narrative theory” has been adapted to “thought theory”, thought the extent to which this is a fresh coat of paint thrown on a rotting ship is up for debate. Narrative theory holds that the power of narrative to capture thoughts is instrumental in the function of standing, to the degree that it’s the primary concern. People are, naturally, capable of thinking about things without an established narrative, but all of the most prominent illustrati have narratives, and even those illustrati whose fame comes from some other source develop a narrative over time, one which demonstrably increases their standing. The biggest problem with this theory, aside from the obviously lack of experimental results, is that it requires a very generous definition of “narrative”, to the extent that a simple plain fact about a person or bare biography becomes regarded as narrative. For my tastes, it requires too much stretching of definitions, or in some cases, awkward redefinitions.
- “Role theory” is a sister to narrative theory, one which posits that conforming to a role is one of the more important things for an illustrati. While not typically posited as the primary driver of standing these days, role theory is often tied into other theories. It does appear to be true that conforming to an established role pays dividends for the illustrati, but there are many reasons for this, and many cases in which defiance of a role pays back equally good standing. Per narrative theory, the prominence of roles relates to their part in crafting compelling narrative. Per meme theory, a role (or defiance of one) allows the meme of an illustrati to take a store of existing memetic power from that role.
- “Emotional theory” sometimes stands by itself, and sometimes lives alongside or as an aspect of the others. Per “raw” emotional theory, it is emotion, as opposed to rational thought, which drives standing, with stronger or more complex emotion (depending on who you ask) granting more in the way of standing. The integrations into the other theories are obvious; “better” narratives produce more emotion, while more emotion results in more thought, increasing “memetic strength”. Again, there are difficulties inherent in saying anything for certain about whether this is true, or to what extent.

It would suffice to say that none of these theories can be fully confirmed or definitively disconfirmed, especially given the tendency of their proponents to make a tactical retreat from their position and say that it may be only “one part” of the whole, or that there might be “mitigating factors”.

#subheader[Whence Identity?]

One last issue of note is the question of how standing gets “bound” to individuals, especially in the corner cases.

Traditionally, an illustrati goes by either their given name or an assumed one, embarks on quests and collects deeds, and sees their powers gradually increase, which generally maps to what we mean by standing. This, however, is the naive case, and more complicated cases are immediately obvious if we use that as our starting point.

- Illustrati demonstrably _do_ gain standing from multiple aliases, pseudonyms, and identities.
- Illustrati demonstrably _do not_ gain standing from taking on the alias, pseudonym, or identity of an existing illustrati.
- Illustrati demonstrably _do not_ gain standing simply for being part of a famous group, through they _do_ gain standing for being a known, acknowledged, or thought of member of that group.
- Illustrati demonstrably _do_ gain standing from other people acting in their stead under the same alias, pseudonym, or identity.

By examining the specifics, we come to the conclusion that there is a moment when identity, in the abstract, “binds” to a person. The most clear example of this is the case of a persona invented by a small group working together, where the created identity will most often bind to the person who first publically appears as the persona, whether or not they were the first to privately inhabit the character.

Once so bound, there does not appear to be any mechanism by which the link between identity and person can be unbound, thus making identity fraud a somewhat rare and niche occurrence among the illustrati. In same cases though, it’s greatly desired that a mentor be able to pass on his fame to his student or child, in which case the usual method is to append a numeral to the name and share a similar costume, but with full acknowledgment that this is not the same person. In those cases, the identity does not actually move to the second person, but they are able to use the existing identity in order to bolster a second one.

But why should any of this be the case?

Here, in my opinion, is where “meme” theory has real explanatory power. We can conceptualize each identity as a distinct “meme”, and while these individual memes as they exist in the minds of individual people might differ in details, we can think of each identity in the ideal, and use Kinshew’s concept of “memetic divergence” in order to conceptualize the distance that a multitude of different ideas might have from each other. Because one illustrati can apparently benefit from multiple identities, it need not matter too much if the illustrati is viewed in distinctly different ways by different groups (as the case where an illustrati is a hero to one region and villain to another), as this can be explained through the same process: multiple memes can bind to a single illustrati.

Of course, actually testing any of this would be fraught with difficulties, and while I can say “explanatory power” all that I want, that’s my own personal opinion, rather than verified fact.